name: Deploy to GitHub Pages

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v3
    
    - name: Setup Node.js
      uses: actions/setup-node@v3
      with:
        node-version: 16
        cache: 'npm'
    
    - name: Install dependencies
      run: npm ci
    
    - name: Build static files
      run: |
        echo "Creating a static build of the application..."
        
        # Create a build directory
        mkdir -p build
        
        # Copy the public directory
        cp -r public/* build/
        
        # Copy the views directory
        mkdir -p build/views
        cp -r views/* build/views/
        
        # Create static API mock data for GitHub Pages
        mkdir -p build/api
        
        # Create clients endpoint mock
        mkdir -p build/api/clients
        echo '[
          { "id": 1, "name": "James Reynolds", "wealthScore": 9.8 },
          { "id": 2, "name": "Victoria Chen", "wealthScore": 9.5 },
          { "id": 3, "name": "Alexander Müller", "wealthScore": 9.3 },
          { "id": 4, "name": "Elizabeth Kingston", "wealthScore": 9.7 }
        ]' > build/api/clients/index.json
        
        # Create events endpoint mock
        mkdir -p build/api/events
        echo '[
          { "id": 1, "clientId": 1, "clientName": "James Reynolds", "timestamp": "2023-04-20T14:32:00", "location": "Milan Flagship", "status": "granted", "confidence": 0.98, "wealthScore": 9.8 },
          { "id": 2, "clientId": 2, "clientName": "Victoria Chen", "timestamp": "2023-04-20T13:47:00", "location": "Paris Gallery", "status": "granted", "confidence": 0.96, "wealthScore": 9.5 },
          { "id": 3, "clientId": null, "clientName": "Unknown", "timestamp": "2023-04-20T12:15:00", "location": "New York Event", "status": "granted", "confidence": 0.87, "wealthScore": 8.7 }
        ]' > build/api/events/index.json
        
        # Create stats endpoint mock
        mkdir -p build/api/stats
        echo '{
          "totalHNWIs": 4,
          "totalRecognitions": 5,
          "recognitionAccuracy": 92,
          "activeLocations": 3
        }' > build/api/stats/index.json
        
        # Create status endpoint mock
        mkdir -p build/api/status
        echo '{
          "status": "operational",
          "version": "1.0.0",
          "timestamp": "'$(date -u +"%Y-%m-%dT%H:%M:%SZ")'"
        }' > build/api/status/index.json
        
        # Create health endpoint mock
        mkdir -p build/api/health
        echo '{
          "status": "healthy",
          "uptime": 3600,
          "timestamp": "'$(date -u +"%Y-%m-%dT%H:%M:%SZ")'"
        }' > build/api/health/index.json
        
        # Create recognize endpoint mock with JavaScript
        mkdir -p build/api/recognize
        echo 'const result = {
          timestamp: new Date().toISOString(),
          processingTime: Math.floor(Math.random() * 500) + 200,
          recognized: Math.random() < 0.6,
          confidence: 0.7 + (Math.random() * 0.3),
          name: Math.random() < 0.3 ? "James Reynolds" : null,
          wealthScore: 7.5 + (Math.random() * 2.5)
        };
        document.write(JSON.stringify(result));' > build/api/recognize/index.html
        
        # Create a modified index.html with GitHub Pages routing
        cat > build/index.html << EOL
        <!DOCTYPE html>
        <html>
        <head>
          <meta charset="utf-8">
          <title>CURATOR | Algorithmic Access Management</title>
          <script src="/spa-github-pages.js"></script>
          <meta http-equiv="refresh" content="0; url=views/index.html">
        </head>
        <body>
          Redirecting to main page...
        </body>
        </html>
        EOL
        
        # Add a 404.html file at the root for GitHub Pages
        cp public/404.html build/404.html
    
    - name: Deploy to GitHub Pages
      uses: JamesIves/github-pages-deploy-action@v4
      with:
        folder: build
        clean: true 